config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-reporting-plugins:
      branch: 2.2.4
      repo: https://github.com/EOSC-synergy/sqaaas-reporting-plugins
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint_fix
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-reporting-plugins git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-sapphire-cattle.sh
        container: qc.acc_gamy-apricot-tzu
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-reporting-plugins find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-brass-kingfisher.sh
        container: qc.doc_scummy-gold-foxhound
      github.com/EOSC-synergy/sqaaas-reporting-plugins git:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-xanthic-chameleon.sh
        container: qc.doc_pretty-jade-macaw
      github.com/EOSC-synergy/sqaaas-reporting-plugins markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-blue-gorilla.sh
        container: qc.doc_sloppy-goldenrod-seal
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-reporting-plugins licensee:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-pink-armadillo.sh
        container: qc.lic_cozy-heliotrope-clam
  QC.Met:
    repos:
      github.com/EOSC-synergy/sqaaas-reporting-plugins cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-apricot-hornet.sh
        container: qc.met_breezy-white-rabbit
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-reporting-plugins bandit:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-cerise-crocodile.sh
        container: qc.sec_hasty-peach-yak
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-reporting-plugins flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-linen-harrier.sh
        container: qc.sty_hazy-bistre-centipede
      github.com/EOSC-synergy/sqaaas-reporting-plugins jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-pink-seahorse.sh
        container: qc.sty_sloppy-persimmon-havanese
  QC.Uni:
    repos:
      github.com/EOSC-synergy/sqaaas-reporting-plugins pytest:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-white-warthog.sh
        container: qc.uni_lumpy-orchid-dingo
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-reporting-plugins get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-ivory-dachshund.sh
        container: qc.ver_homely-heliotrope-saola
timeout: 5400
