config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-reporting-plugins:
      branch: 2.2.4
      repo: https://github.com/EOSC-synergy/sqaaas-reporting-plugins
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint_fix
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-reporting-plugins git:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-platinum-panda.sh
        container: qc.acc_skimpy-celadon-pig
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-reporting-plugins find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-cream-gorilla.sh
        container: qc.doc_pretty-ecru-iguana
      github.com/EOSC-synergy/sqaaas-reporting-plugins git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-champagne-lionfish.sh
        container: qc.doc_shaggy-asparagus-greyhound
      github.com/EOSC-synergy/sqaaas-reporting-plugins markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-amber-iguana.sh
        container: qc.doc_homely-brass-schnauzer
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-reporting-plugins licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-tan-barracuda.sh
        container: qc.lic_snoopy-wisteria-wolf
  QC.Met:
    repos:
      github.com/EOSC-synergy/sqaaas-reporting-plugins cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-persimmon-zonkey.sh
        container: qc.met_tacky-cerise-moth
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-reporting-plugins bandit:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-sapphire-fowl.sh
        container: qc.sec_flabby-viridian-squirt
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-reporting-plugins flake8:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-aquamarine-dane.sh
        container: qc.sty_fuzzy-khaki-warthog
      github.com/EOSC-synergy/sqaaas-reporting-plugins jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-seashell-zorse.sh
        container: qc.sty_lanky-harlequin-dormouse
  QC.Uni:
    repos:
      github.com/EOSC-synergy/sqaaas-reporting-plugins pytest:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-brass-crane.sh
        container: qc.uni_foggy-scarlet-capuchin
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-reporting-plugins get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-copper-chimpanzee.sh
        container: qc.ver_pretty-yellow-macaw
timeout: 5400
